// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmokeTestLogin.Data;

#nullable disable

namespace SmokeTestLogin.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20230827153554_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("SmokeTestLogin.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_passwordUnHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Marion Hirthe",
                            Password = "CECBFE2904398D9BD673FC3649A353FCECFA5E2DB7C3AA38581162769FB5A244:34ADA6ED522425CFAA9557A4744863D8:500:SHA256",
                            UserName = "Marion_Hirthe25",
                            _passwordUnHash = "M5hl&u"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Tricia Medhurst",
                            Password = "738F7D54A236A2219D5F1B932E9EA11125C7240506B00DC60011D9521FD60936:20CE77D6F9AF5977E29AEFA5C3D97F60:500:SHA256",
                            UserName = "Tricia.Medhurst48",
                            _passwordUnHash = "Igp3bt#"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Simon Rogahn",
                            Password = "AD783D007FA0BE1DF83F94929DA98115ABD1AE9B23F75A8BAB5D9593387A16A6:F8390F08C886AFDD5FE2F772266F256B:500:SHA256",
                            UserName = "Simon_Rogahn",
                            _passwordUnHash = "U%mm0iz"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Tonya White",
                            Password = "B6133721AF9B444C0D4C521EC8DB857793C4C32ECCBF7540CDD553C8B9EC6DCC:95A53B4F20AD150F9D5D47861D65DB0C:500:SHA256",
                            UserName = "Tonya_White25",
                            _passwordUnHash = "hD$sxxpws3"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Gene Wisozk",
                            Password = "4536AD5B015B094A36C4730F505449B7A57742A749F6AE58CAD68205631F2387:8072CF862C012CE54445BB9984532009:500:SHA256",
                            UserName = "Gene.Wisozk",
                            _passwordUnHash = "xl&9eilB"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Marion Cruickshank",
                            Password = "4F078ABBC10F8E4899966D4C1834EF03FF4E3BC03A529D4E78AE28520DD57AD0:6BF359EDDA02B0BBE732DC01C1984EA6:500:SHA256",
                            UserName = "Marion24",
                            _passwordUnHash = "Pgqt9k%"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Bill Schulist",
                            Password = "D5C3FAEC1B445795238563B4A8D462D906E9EA51C4B7B5EFE3120CA87E30612F:09325A38005DB116E9EF432CBA6924DB:500:SHA256",
                            UserName = "Bill58",
                            _passwordUnHash = "a%8oexvVl"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Verna Hilpert",
                            Password = "A1F2D705F342DC57427DFC619F232DC5B8F9EDFE026E3FD0B0C87E2DAA79DBCF:B4D5E4A262A7D9DBEC4C4AC4EC577CAF:500:SHA256",
                            UserName = "Verna_Hilpert98",
                            _passwordUnHash = "dwxG0%"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Jackie Goldner",
                            Password = "16FC8210AE3507964190FF801923F7647D8432784020BFDC2E112F6BF7FBBA91:6D67966203319F8B9C3A52FDA63DB1BD:500:SHA256",
                            UserName = "Jackie8",
                            _passwordUnHash = "q%Hx0z"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Jaime Davis",
                            Password = "B82A6B1366478FD0AF3CD8FE23D95D95646D067330915DB082E4AE0BB87B7A80:BC268B75D695F4E4B2D316B1D263B54E:500:SHA256",
                            UserName = "Jaime_Davis",
                            _passwordUnHash = "idHr%a2reo"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Rex Turcotte",
                            Password = "9BFABDD348BFA2DC48F80EFB19407EE15B9E258A2BC04AEA17605ECA78FA7712:51CF3FC980CA377943D007CE67EB676C:500:SHA256",
                            UserName = "Rex14",
                            _passwordUnHash = "hKrej&3"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Lindsey Lueilwitz",
                            Password = "5DF1596B81D35ECCE50BB94B4229555F04FFE47D5635E8C2B4BCC8E9345258DC:3FDE2C8E356DD6F478ABFFD2926198F4:500:SHA256",
                            UserName = "Lindsey_Lueilwitz97",
                            _passwordUnHash = "z#w7fzIpzz"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Julia Bergstrom",
                            Password = "76659225B5D74BA91622ACD4739F9FFAE955F4BC5269F432C8A034DD0099CD81:07EE112775DA51CF25686EFEA455AF8F:500:SHA256",
                            UserName = "Julia41",
                            _passwordUnHash = "&Irinl6uz"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Lillie Kilback",
                            Password = "A75DFC55127579731D246806CFE6087969C586D785E186DD54BA7CA8B72B6305:0807F4CFEAE827994496FBE608D5A448:500:SHA256",
                            UserName = "Lillie.Kilback",
                            _passwordUnHash = "ok&nqG2"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Rosemarie Kohler",
                            Password = "EECB1CFE672F0D4C667CD5090A7A7912EF5BA780B9F14A6E2139844C58CA526D:880160288731A2E8F8025DEBB6CA9966:500:SHA256",
                            UserName = "Rosemarie78",
                            _passwordUnHash = "ak8J%i"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Salvador Pouros",
                            Password = "9F67EFD333FA17951A1AD5F6E854E60685A15C5A4907CF7A0548DD55F8E37A59:D83369321022E1AEE899EDCC272DD461:500:SHA256",
                            UserName = "Salvador55",
                            _passwordUnHash = "sShpq%6"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Jo Berge",
                            Password = "B3262A52DED7484EF244176F4D22D19B9B04B7EB7C3FF7AA2D12D0E1D4947CB9:05004DCBAC67327BCD78204C8856E64C:500:SHA256",
                            UserName = "Jo58",
                            _passwordUnHash = "#bvduQ7d"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Katherine Konopelski",
                            Password = "4974AD5729958DD2BB979B3A3EF5E2D5E977371A742B4100CB1B38DD638032AC:B4D9A9867DD842A1720C0D1643FEFEF3:500:SHA256",
                            UserName = "Katherine_Konopelski",
                            _passwordUnHash = "am#vEjy6"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Abraham Schaden",
                            Password = "4FF1501E8225E5011EE74EA8DB98BA43ED17C3F390E14021FB541DA137370F57:B12823C4FBC77CEF4958C043AE149436:500:SHA256",
                            UserName = "Abraham.Schaden91",
                            _passwordUnHash = "nvaHy3x&"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Toni Robel",
                            Password = "AC923FB277A8335AC0966EAAA12397D71D339A997855DF602D228858861BDD88:7845A53B61C5EB4C4CA6CC7F93892C5B:500:SHA256",
                            UserName = "Toni88",
                            _passwordUnHash = "dvH%7bu"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Tabitha Schmidt",
                            Password = "77EFF59651A762ACE98FCC8CF09F95BC5310F5AE32EDE6AE0FA561D1B721EDF5:A59751F26C88FBF063256790F90F1CFA:500:SHA256",
                            UserName = "Tabitha.Schmidt",
                            _passwordUnHash = "b&pMljlgu1"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Aaron Ferry",
                            Password = "63C87F28D1C4E295992C2ACEAF11B1C42DFD7B0D9AC5C0E30EB4A5A9C374710E:CD93F86F9A9C51BAE53ACF151007168E:500:SHA256",
                            UserName = "Aaron.Ferry",
                            _passwordUnHash = "pE$j4fa"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Albert Gleichner",
                            Password = "AD110EF6B95E062EE85F495FCD194F62D513DFD29092899EB9A883F56D5544E8:2662F8BB5E6CE108A9ACB1B044D723A5:500:SHA256",
                            UserName = "Albert26",
                            _passwordUnHash = "p5uz%U"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Joy Rempel",
                            Password = "F1AC40106F4EA9225DEBAFFC4E4139B8459251D6EE7C568AABB995A28828897A:5E6F80ABAD2C13360233713BF43EB6F8:500:SHA256",
                            UserName = "Joy.Rempel17",
                            _passwordUnHash = "wvm%jF0hwb"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Beth Parker",
                            Password = "D54FA6E750D99D7281A9FE212C0122CC036B66F923464499F9590F5CD593AF9C:A8D25BB59BA6DFB89861E14AAE17343A:500:SHA256",
                            UserName = "Beth.Parker50",
                            _passwordUnHash = "8lHr#vy"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Gilbert Kozey",
                            Password = "C929EB485838C53C40E401FC818131E7AA561621CF237A55F5AC19878CE9A273:14348DD97ADB3DFAB3E2DE69FDEC429A:500:SHA256",
                            UserName = "Gilbert_Kozey46",
                            _passwordUnHash = "Et6yqf&"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Lorene Pfeffer",
                            Password = "4933BECDFF3C1F3BFA93C404B31D3CBB2E851A382B99CAC61C98DA64D831E79C:7A00D0BB6EC05A58A260AE3F06761E22:500:SHA256",
                            UserName = "Lorene_Pfeffer70",
                            _passwordUnHash = "Qx8xc&"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Whitney Doyle",
                            Password = "F659535E1AFAA665BEBACD87177586EAE613000653F4A1E27EC8947B356B34AE:B198569BEA4E4115F429B1E6BAE02952:500:SHA256",
                            UserName = "Whitney.Doyle41",
                            _passwordUnHash = "nXh7mdi#"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Valerie Trantow",
                            Password = "84B2384C4F212CDC2584EE24E60ED9FA0650F8A8680C1A4EFB6C70576337808A:F8A873A36A6F2BA63EB8CE802C5D1489:500:SHA256",
                            UserName = "Valerie48",
                            _passwordUnHash = "o0ab&dIv"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Tricia Walsh",
                            Password = "091E90A70017608733281107937F43D9BE8F3EA78F3055965815885EDDEF39D5:AA44A22A8AFDDEEDDA51C0C196D3D19D:500:SHA256",
                            UserName = "Tricia6",
                            _passwordUnHash = "n8q&nA"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Dana Hayes",
                            Password = "9E0DA669E701B63A04D1E0D3AD1BB1BC9B7737A0701CD5DDA3728C49311776CF:1AB287AE7B385F97452FD9F57CD92690:500:SHA256",
                            UserName = "Dana.Hayes",
                            _passwordUnHash = "Mbwl%bie6"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Eduardo McClure",
                            Password = "D09711B3FE15B24485A5CE0C2363CCFA23A6024B9B91A325A73DAEEDECC58233:B9F989161C09D4C961E5FADEF281DEA3:500:SHA256",
                            UserName = "Eduardo.McClure9",
                            _passwordUnHash = "&wl8vjbIkx"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Heidi Gibson",
                            Password = "7F0B0856F0EBCEC5D6A0B900A0E809C43C8292D52010AAA4255A4C424D2A46BC:F9EC0F56697F8193724ADCC6739C1E59:500:SHA256",
                            UserName = "Heidi_Gibson69",
                            _passwordUnHash = "5awXs%"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Gustavo Ryan",
                            Password = "7599CA66810D13C45B5B9A301AEA3C3818E3917184AE6FF9C6BC716A28182247:EDD69B46307482E2F0EB8C94350075DA:500:SHA256",
                            UserName = "Gustavo47",
                            _passwordUnHash = "3dghWhaq#"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Kenny Daniel",
                            Password = "8FF1E0BA850468C650D9A98C8AF0D3F93AF9E0BCDEB547534CCDB0AF52316029:1EDAEE35EBFF36C002C0CA6FAAE318FD:500:SHA256",
                            UserName = "Kenny_Daniel",
                            _passwordUnHash = "i%kmbTuy3m"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Chad Nikolaus",
                            Password = "F99F42ED66EBE73E4FBEAC046EB533B85E6731820C89B6D828BC81926BADEE21:A042F69420CC5E478C564A6B9F28430C:500:SHA256",
                            UserName = "Chad_Nikolaus43",
                            _passwordUnHash = "T9vfies$an"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Pamela Littel",
                            Password = "C182035176F7809B6539F04354394607CE46F2DCECAD3B6BBE55F54B4171A366:F5C1A88EFA844EBCFB2E32A55B21FF1B:500:SHA256",
                            UserName = "Pamela26",
                            _passwordUnHash = "#zx7bpiqlL"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Irving Mills",
                            Password = "D1D9D93F50871406FA61A3FCA02D6867B93AAC2D7F38478E74F99E672E5F48CF:E06C1FB9058D554BB91856D0BEBA1870:500:SHA256",
                            UserName = "Irving_Mills10",
                            _passwordUnHash = "bfuwH1x&vt"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Emily Balistreri",
                            Password = "F12F61C0405408A29497811B22659EE867ED54E9B72AD7AE94207C661448A59B:3931B6B144ADFC4AC324833EDF71B426:500:SHA256",
                            UserName = "Emily.Balistreri30",
                            _passwordUnHash = "j$jgf0Tch"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Eula White",
                            Password = "38D1DA13DBB6340011CD2FEA3581F8802E0AA3FE5A8D41ED07393A737F1F6B59:C9632475D0AB25D64FB0C35F69AEC3EB:500:SHA256",
                            UserName = "Eula.White68",
                            _passwordUnHash = "u&j7Ew"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Nathaniel Kulas",
                            Password = "BF509DB40CBCF44548595146F05106A01C87DCAE59A3D6F5E036FD9D76236151:7E84288E0A685EA840645F27D340B9E9:500:SHA256",
                            UserName = "Nathaniel87",
                            _passwordUnHash = "k&1hmeT"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Conrad Conn",
                            Password = "088C2B444C497145A7EC13C8E6DEA0FD953C01383B074987CDA9FF4DFEFE88FE:B352B9944D5620E807AE0BBFAC6DC41A:500:SHA256",
                            UserName = "Conrad.Conn58",
                            _passwordUnHash = "ooE5xobio#"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Jamie Wuckert",
                            Password = "B4D03229192955903D687EA6369D7F0177ED45ACB4BFF1B4E2D326C5BF9B966D:3D964BFE5C46A47081FCFEBCFEBB5143:500:SHA256",
                            UserName = "Jamie_Wuckert",
                            _passwordUnHash = "%pbV4zyk"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Lorena Kuvalis",
                            Password = "C67CA343A1EBA42A965506DBED1A4ED279824A80E032E1B1B3A117A5D7442B42:16D51C471067DE2F4813CF4CFE2C67A8:500:SHA256",
                            UserName = "Lorena.Kuvalis",
                            _passwordUnHash = "a6iMmj#d"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Julius Cassin",
                            Password = "BA303ACB98FB93A5AF275B2F63718806634A9DF5671F1829C35D523B2669C35E:3DB1A46E1781AD2EFC5752E98AB6319B:500:SHA256",
                            UserName = "Julius31",
                            _passwordUnHash = "zu&q2N"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Wallace Connelly",
                            Password = "BB398B1EA2CCE41CEA3CE47306F17FE284545286E652006BA9F93110B963DA2A:73BCB7FD42C35D6BD32426C39937D306:500:SHA256",
                            UserName = "Wallace56",
                            _passwordUnHash = "gNv7fgf&"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Lee Wiegand",
                            Password = "33DD9177B5B653BCAF69441D642F1E05F8DD16B60DC43B4919AF04F552F8651D:AAC0B8A7E2DE1511206E122071807D59:500:SHA256",
                            UserName = "Lee.Wiegand82",
                            _passwordUnHash = "#7szVxpjs"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Tommie Wiegand",
                            Password = "A5CD032865128C898317BFDAE8B910858DBA120FEB7A7CB7C219B13C474DBA0D:85EE8330CE0FA6C1285E46BCC20C8725:500:SHA256",
                            UserName = "Tommie.Wiegand35",
                            _passwordUnHash = "ccwY8$"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Russell Bernier",
                            Password = "709F78B346379BE4DC583E1EC6883E06107566ECE166A02A6605FDBCAF888F71:0679CE1EDB60EC8F3B16B60E99DC63DB:500:SHA256",
                            UserName = "Russell12",
                            _passwordUnHash = "6btIm#"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Harold Rolfson",
                            Password = "3D2DD47BFB65CBF04CB1FC42E8FD609F7399C71D6406075FF275E882BC10A4FB:AF1424A1DC81C74CCDF2E88DCBC3D2A5:500:SHA256",
                            UserName = "Harold_Rolfson",
                            _passwordUnHash = "qg8$hJj"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
