// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmokeTestLogin.Data;

#nullable disable

namespace SmokeTestLogin.Data.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20230825002937_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("SmokeTestLogin.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_passwordUnHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Ricardo Bergnaum",
                            Password = "5D494E43BCD735404384003C5678BDC7F7967D639FB57D0A3C2A1B1D1C84A3E9:A05ABEB251B826C7E6887D5CEE7CE1C9:500:SHA256",
                            UserName = "Ricardo_Bergnaum",
                            _passwordUnHash = "jB013t07hZ"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Teresa Pouros",
                            Password = "3C11671921A563059084486005CDCA4C58DD4F5A40D98D320E78AABC5183B55A:3D7370257343D340E09EF05F0D8C691D:500:SHA256",
                            UserName = "Teresa4",
                            _passwordUnHash = "rAPrnyGuMZ"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Wilbur Bogisich",
                            Password = "C801FED69CD712898F045431F9595B7E9CDC661322F9DA0413544C675E7F9662:7253DC35575E073F101A4B3483B8BB9D:500:SHA256",
                            UserName = "Wilbur.Bogisich",
                            _passwordUnHash = "TmRx__ByWF"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Robin Buckridge",
                            Password = "3EC29C2CDFDBD6677048A975FF389C15416548E4107DE67E68262E0CB46F7B87:C1973B68189B7016BCC83FFF4D6FBC78:500:SHA256",
                            UserName = "Robin_Buckridge",
                            _passwordUnHash = "v00_Qfq1T7"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Frederick Runte",
                            Password = "699ADCC6CDA281F64EF3F89C94433C5054D05FF3FA374D45E8427B17213DE702:80E5DCAF3FB22770AD074565AEAB7191:500:SHA256",
                            UserName = "Frederick.Runte70",
                            _passwordUnHash = "YKTTigZkyh"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Janice Stokes",
                            Password = "754768199B368E30550FADE1326B243B37072B6E053A2098A1F65059506F6F13:7F8A9042002BBC4752243BD7503FC9AF:500:SHA256",
                            UserName = "Janice_Stokes53",
                            _passwordUnHash = "K2cMxtXozG"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Beth Frami",
                            Password = "A5701695D4B9B1E48E35DFD6786EFC97C500BDCECC0EDA25D06937D559FF0D78:8FEA71BEA220263BBB5C2896A49FC346:500:SHA256",
                            UserName = "Beth_Frami95",
                            _passwordUnHash = "ktgofFSdmq"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Rebecca O'Reilly",
                            Password = "2E0E5FA841249EDA7DAE76989C2A461B701FC34F6AC440BBDE44DFADF5BF7FE2:9A9B7C302C7E805098398DAC36EED922:500:SHA256",
                            UserName = "Rebecca30",
                            _passwordUnHash = "vAhfW3Lcg_"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Jill Franecki",
                            Password = "1424470256C9C4A3968148175CCAD0B697EA0109E417AF7FD02F6B1A15F142BA:54993F3841E0F9912A9947B39B1363CC:500:SHA256",
                            UserName = "Jill_Franecki78",
                            _passwordUnHash = "lCw98XGHhr"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Jessie Abshire",
                            Password = "E2AE9192396217C9786E3EE0C9D184A3AFADF0B74D5ADA887D4E32BBF07F2171:C1157A6D8E8C328634824BE87371434C:500:SHA256",
                            UserName = "Jessie_Abshire",
                            _passwordUnHash = "Y6R86RLPUX"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Robin Lockman",
                            Password = "D10BC7DF5D2DDF617EB9D1A3213644E7F4697E90B7C3930BDE5A424B17F5A590:192C7FE8DF910B3B31FD2FF147770CFD:500:SHA256",
                            UserName = "Robin.Lockman",
                            _passwordUnHash = "d91Pxxzz_I"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Latoya Gerhold",
                            Password = "ADAFA8D2620E6760918096F61E469557B310F6014701C4339D6207BA896C7BDF:8DA48F2C5EBFAF4953AD42FD33A1530E:500:SHA256",
                            UserName = "Latoya.Gerhold",
                            _passwordUnHash = "guh39kJmOW"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Todd Johnson",
                            Password = "D57E958A9E315C7692A2D7FCA31F00C0EE1A1E6B1D4430121148EDDE24B5B033:A6E6DDCE20ED46D0FE59E756DEF84F57:500:SHA256",
                            UserName = "Todd_Johnson36",
                            _passwordUnHash = "ORCrjvMYss"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Grace King",
                            Password = "BC83054943F25A53923A53EF689F6D1D1651ECA7BA4B2C208481278C626CEE9F:9B8CADBB8727A6D7DFE7C18BF1EBBD0F:500:SHA256",
                            UserName = "Grace_King94",
                            _passwordUnHash = "IGBXiL6Clq"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Garry Harris",
                            Password = "FA9583DD958875E5CEBB0AA3062D6ADA2D6F8DC674CAE35E6CFA0C5DE9D502CC:F6F0FD48B9E2B84F9DE9C9F54316CA9B:500:SHA256",
                            UserName = "Garry73",
                            _passwordUnHash = "BkvS3D2Ynr"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Sheila Parisian",
                            Password = "6790503A6959D5CFCD476F6C2B5F42FFC8021E3732B7665495EBE34FBE104991:D0079888A108B3FB7D36DE7C5F4F4B03:500:SHA256",
                            UserName = "Sheila_Parisian",
                            _passwordUnHash = "aBhzp9rO64"
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Max Kassulke",
                            Password = "D95291698627FA44E1CB06027F920894E04320636F6FDF450FAACD1EC9420565:40F3B9DEBAB61BE9177F629F2411882E:500:SHA256",
                            UserName = "Max_Kassulke",
                            _passwordUnHash = "ur3DyPKlCS"
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Molly Cummerata",
                            Password = "C275592599AC993F3CEE68B99802B29AC7AE3DDF2E41B08752305BC510AFE1BD:CF4A2267E51A3EC416B8366F7516BADD:500:SHA256",
                            UserName = "Molly.Cummerata",
                            _passwordUnHash = "5OZBvGEgDH"
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Stacy Walsh",
                            Password = "D561B3F1F6D549E04F87C08DCB29BB1907079EA51C1EA973FCB215F6C0AB0DCE:7ADFC0EBF4D6968DCAA1C9B352B98D5D:500:SHA256",
                            UserName = "Stacy.Walsh",
                            _passwordUnHash = "49656UIjeX"
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Clark Wiegand",
                            Password = "A2EF5F1AF4BB430A56C8299F8E4743C0E200E7EA923E0CB5FC8A2DCD4099678F:08F81FA764CB605101D51C756EFE418C:500:SHA256",
                            UserName = "Clark.Wiegand82",
                            _passwordUnHash = "UXiqDx9u40"
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Fred Hand",
                            Password = "D5ABE9E660D0AB1BA583E84DFD9F5BB03628D3E7A814EF60D68CB6AE8DF98BAD:97715C31FF9DB45E7A70909D90F7ABA0:500:SHA256",
                            UserName = "Fred_Hand",
                            _passwordUnHash = "xgENFbqW86"
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Erma Pfannerstill",
                            Password = "2EA270CC1501F54FA3C27CB798A963DD76B5EE2E283C09B5114DEF256C77816F:C390A56B644F75F3C4A34A8CF0BFF2E0:500:SHA256",
                            UserName = "Erma72",
                            _passwordUnHash = "ZgEaXTA6Ok"
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Patsy Welch",
                            Password = "929AE5226E7A51EDABD24E1F508080E8465A0B00E2A3E87F2B2237FB92A16531:4BC0AB7A584D7A3FD4406A72CB9AE64E:500:SHA256",
                            UserName = "Patsy.Welch34",
                            _passwordUnHash = "KsBI1WKa7P"
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Shannon Thompson",
                            Password = "FD2134CC2B196F1250EBFBF3171079A84579067221BEDF9C0330C0CF26303785:1D548C7D413503DE334804239015B14D:500:SHA256",
                            UserName = "Shannon61",
                            _passwordUnHash = "qs18QBSMKl"
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Lindsay Harris",
                            Password = "2DC920DEFB3EB65261CF9493340F1F30E59DF33FCAF44CDFF22034912308814C:3E559EEE106A223DCA5CA703200BE729:500:SHA256",
                            UserName = "Lindsay_Harris68",
                            _passwordUnHash = "xsGBXyu01w"
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Jacqueline Erdman",
                            Password = "FD3587C36B89A69D5D31A53AC23D864889F1C2B25228B688A2D402292BAC978C:AA959EBF5F4428123B83ECFD84250CAE:500:SHA256",
                            UserName = "Jacqueline_Erdman",
                            _passwordUnHash = "zQsNlXgOmO"
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Candice Kertzmann",
                            Password = "CD82859C377ABAC2B7C105BB4F242707411793FBD4F61C81AA6359F548304196:FC1AD68E61C85CF126D9DA593FF997E3:500:SHA256",
                            UserName = "Candice_Kertzmann",
                            _passwordUnHash = "CACMqRDTtL"
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Luz Heathcote",
                            Password = "13A8D94CF5E6BFB875A2252A1F325A3578F7616E9D3446C5D0C975864216BE29:1D7B7F36B3A740D02BBEFF8BD7622FC1:500:SHA256",
                            UserName = "Luz.Heathcote",
                            _passwordUnHash = "tUhs7QIJDM"
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Meghan Tromp",
                            Password = "510C00E7C8393E412A26DF8F16A073E3B7BDD9C2B7B12DB297A697EA89BC2134:123E88686F719D44DEC2D3F64A8E8358:500:SHA256",
                            UserName = "Meghan.Tromp",
                            _passwordUnHash = "WBJ5A38ECM"
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Henry Von",
                            Password = "ACCBB6021B2291FA30E739A9C18EA729F0434566AB9F495FDB954A59F3A2FD6B:DCDC6189E60AAC90A75BE060AD2EEA96:500:SHA256",
                            UserName = "Henry_Von9",
                            _passwordUnHash = "S1WvMFMhqf"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Kevin Schroeder",
                            Password = "C5CEFA95766CAF943207493EFA44BE125D41834DCC1361D7FE1CAEB7A372E533:E31774688BB573C2441CA81366748E5C:500:SHA256",
                            UserName = "Kevin_Schroeder38",
                            _passwordUnHash = "mt6BuhgeHH"
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Dominic Green",
                            Password = "D46F33A57A73E8054E71E292566FA3D2BA3F2C69BEB5B0A7553EEBB2AF2DEC1B:B38AF2A477D93C45B95C9B7F81BC6807:500:SHA256",
                            UserName = "Dominic79",
                            _passwordUnHash = "SMVBSm5iCa"
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Katherine Ullrich",
                            Password = "C97CD9605FD29A0FF0B9C09D0F5A0770892B82DF5BA98BAE516CCBCF26B9BB0B:1EA8D7A64587EE58CC0B48D2A74F5963:500:SHA256",
                            UserName = "Katherine_Ullrich31",
                            _passwordUnHash = "QxIdfh9ozy"
                        },
                        new
                        {
                            Id = 34L,
                            Name = "William Barrows",
                            Password = "6C88FBD0E68F312CBCC5DBC3D5B464322D000D6EDE570D3D280CFA878B3C45AD:3E84DFC24493ECB3E5471ACD319304E1:500:SHA256",
                            UserName = "William_Barrows",
                            _passwordUnHash = "OyLvif8bAO"
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Levi Wilderman",
                            Password = "0F66840A87095976C63E20E5039CB8C447E0678E4808D2734356347D4FDFC638:B6DA7D95AE44AFB3EA8C3BB795461F53:500:SHA256",
                            UserName = "Levi92",
                            _passwordUnHash = "TWsAbt3OCe"
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Herbert Prohaska",
                            Password = "6513C5E5C2F0C42B2EBF0774BF6513514B4609D33F9A8AB6408D6487A034E0AC:0A57687F857630DB34EF074B024F37CD:500:SHA256",
                            UserName = "Herbert.Prohaska6",
                            _passwordUnHash = "QS6GEa04uS"
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Rose Beier",
                            Password = "CFAA7B7E5D8060E93B652C972FF0376983A8DCA45F7E6B805DB9089B1200F98E:A30B3E9367EAB37278ECC4BFC05C433C:500:SHA256",
                            UserName = "Rose.Beier45",
                            _passwordUnHash = "HG9RUk02V8"
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Sophia Rath",
                            Password = "88CF9567E81247C36A87ACD91DBA30DA02F52F52DC6CF598C9F78DEF2D4090F6:A9E962BC4AF184774EE9503CA3500278:500:SHA256",
                            UserName = "Sophia_Rath",
                            _passwordUnHash = "U_SLZG1g7M"
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Jaime Corkery",
                            Password = "5C0C8E000DF21DB7EF7A6158C99B27843B20214F1B40C1DFF083D5660607D589:B9E3AF680AC07E6AAA33C610D4AB153A:500:SHA256",
                            UserName = "Jaime_Corkery",
                            _passwordUnHash = "Z1XxrbHXnT"
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Faye D'Amore",
                            Password = "1BA56E276D96AA60AB727CE929C112CF6B8DE9A78EA446105056F92D2F50A979:E9BC06B107065B9411AD19DB69A65F40:500:SHA256",
                            UserName = "Faye.DAmore",
                            _passwordUnHash = "G9T2m84uiZ"
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Susie Beer",
                            Password = "7BE69A09B3C4BAB5115C78A92AC1B47E5182FAA021A976D2A2EF250D74416B4B:87DC7125BB5D62081D20578A6825CC91:500:SHA256",
                            UserName = "Susie_Beer",
                            _passwordUnHash = "F3N2GSVgE9"
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Geoffrey Stamm",
                            Password = "08C4D92E24454AFD3AEA4A30F557472300E1E0E42C6F3B69B8E7FEDEBAD3D66A:026051704000E97E377B828C100A50BE:500:SHA256",
                            UserName = "Geoffrey_Stamm81",
                            _passwordUnHash = "_LIdqL3yrg"
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Cynthia Glover",
                            Password = "2EBEFA2C7E6A89483FCECE30328E28D74795F7A3C858A54547BD92AF89B297A5:0296FB6BE9645B4A043AD5FA1DE93F39:500:SHA256",
                            UserName = "Cynthia_Glover9",
                            _passwordUnHash = "b_LB1BENlo"
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Margaret McLaughlin",
                            Password = "77E60A1A7DDFEA0C311AB28A6EACBCA0144CADA42A60080FF7071C25F8978323:9F9E465D19EF8028542D6167EEF41550:500:SHA256",
                            UserName = "Margaret_McLaughlin73",
                            _passwordUnHash = "WSsFv94ELM"
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Kayla Daugherty",
                            Password = "56B5C5ECAD9A2A42786F0726E558E2DFCD825EBF664226981A0548B9CD252FC6:40A9455E5DF8D445AD3EB221D0C404CA:500:SHA256",
                            UserName = "Kayla_Daugherty",
                            _passwordUnHash = "KIcbrIh14x"
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Lionel Wintheiser",
                            Password = "2B6DB05FE2398C2F82B0E3AD5900417118606C717771C0CE7D1F59C6766613F8:740704ED316E2AD95547705F6A9D46EB:500:SHA256",
                            UserName = "Lionel_Wintheiser",
                            _passwordUnHash = "YPpZQO9kzX"
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Gilbert Kessler",
                            Password = "4486D15BA423274EBD595A16119754AC0192F6F162E8E72002D0A19CD6D0CE43:D202803CD6DEF30CBCCD501A0D225162:500:SHA256",
                            UserName = "Gilbert.Kessler88",
                            _passwordUnHash = "XUDZrDp2lI"
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Phil Fadel",
                            Password = "C13A611B9EF0AD82A84473748AF6D23F45E763558FE0ED0641FD431E1FBD49EA:68EFF4D1012BA40AF81E9209273407B5:500:SHA256",
                            UserName = "Phil58",
                            _passwordUnHash = "BGk5wpd6of"
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Janis Bernier",
                            Password = "29D183AF4628DCFBB9A0EE0451775F9E2EFCAACD1CC40739B0C6B523ACA75339:8FC0C75A89C0B291CB4A3CF858F81DE0:500:SHA256",
                            UserName = "Janis.Bernier89",
                            _passwordUnHash = "E_MZS6BbTb"
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Jamie Yundt",
                            Password = "76A306E48837C859C737C60BF2D3AE06FF5F265FF5ED4C4AC8641ABC4A40E446:C51F6E13ADB3089640136DAA4C88FEB7:500:SHA256",
                            UserName = "Jamie68",
                            _passwordUnHash = "KU9CaZEBL1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
